### ISSUE TITLE
Using script on Edgerouter X with GoDaddy fails

### ISSUE THREAD

**Issue by nahoj74** [hungnguyenm/edgemax-acme#10]
Decided to get a certificate for my Edgerouter X and found this project. Registrered a domain with GoDaddy and got the API keys. 

Implemented script according to the readme 

```
mkdir -p /config/scripts/acme/dnsapi
curl -o /config/scripts/acme/acme.sh https://raw.githubusercontent.com/acmesh-official/acme.sh/master/acme.sh
curl -o /config/scripts/renew.acme.sh https://raw.githubusercontent.com/hungnguyenm/edgemax-acme/master/renew.acme.sh
curl -o /config/scripts/reload.acme.sh https://raw.githubusercontent.com/hungnguyenm/edgemax-acme/master/reload.acme.sh
curl -o /config/scripts/acme/dnsapi/dns_gd.sh https://raw.githubusercontent.com/acmesh-official/acme.sh/master/dnsapi/dns_gd.sh
chmod 755 /config/scripts/acme/acme.sh /config/scripts/renew.acme.sh /config/scripts/reload.acme.sh /config/scripts/acme/dnsapi/dns_gd.sh
```
First the edgerouter x doesn't like the "killall" command, though the UI is pretty much gone after the command. 
Second I get "[Mon Jul 26 11:15:52 UTC 2021] Can not init api for: https://acme.zerossl.com/v2/DV90."
 
![image](https://user-images.githubusercontent.com/31799093/126981188-5613aeb7-3e72-4ffb-b071-48b3f4b04db6.png)

I guess there are some additional configuration steps needed?  Assuming I want to have a cert from Letsencrypt, how do tell the config to go there?

**Comment by dmengelt** [comment]
The following worked for me:
1. Create a `/config/scripts/acme/account.conf` file with the following content:
```
DEFAULT_ACME_SERVER='https://acme-v02.api.letsencrypt.org/directory'
```
2. Run the `/config/scripts/renew.acme.sh` script again

The "problem" is that ACME switched from letsencrypt to ZeroSSL https://github.com/acmesh-official/acme.sh/issues/3472#issuecomment-892752538

**Comment by nahoj74** [comment]
> The following worked for me:
> 
> 1. Create a `/config/scripts/acme/account.conf` file with the following content:
> 
> ```
> DEFAULT_ACME_SERVER='https://acme-v02.api.letsencrypt.org/directory'
> ```
> 
> 1. Run the `/config/scripts/renew.acme.sh` script again
> 
> The "problem" is that ACME switched from letsencrypt to ZeroSSL [acmesh-official/acme.sh#3472 (comment)](https://github.com/acmesh-official/acme.sh/issues/3472#issuecomment-892752538)

Solved it for me as well. Thanks!

**Comment by hungnguyenm** [comment]
Closing this as #17 forces ACME to use Let's Encrypt instead of ZeroSSL.
