### ISSUE TITLE
Error with Cloudflare DNS

### ISSUE THREAD

**Issue by jimmyeao** [hungnguyenm/edgemax-acme#5]
root@ubnt:/config/scripts# sh renew.acme.sh -d ubnt.mydomain.com -n dns_cf.sh -t CF_Token -k "mytoekn"
[Fri Dec 13 10:10:32 GMT 2019] Stopping gui service.
[Fri Dec 13 10:10:33 GMT 2019] Executing acme.sh.
[Fri Dec 13 10:10:36 GMT 2019] Single domain='ubnt.mydomain.com'
[Fri Dec 13 10:10:36 GMT 2019] Getting domain auth token for each domain
[Fri Dec 13 10:10:41 GMT 2019] Getting webroot for domain='ubnt.mydomain.com'
[Fri Dec 13 10:10:42 GMT 2019] It seems that your api file is not correct, it must have a function named: dns_cf.sh_add
[Fri Dec 13 10:10:42 GMT 2019] Please check log file for more details: /var/log/acme.log
[Fri Dec 13 10:10:43 GMT 2019] Starting gui service.

no further useful details in the log. using https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_cf.sh
for the DNS api

**Comment by hungnguyenm** [comment]
Hi @jimmyeao, sorry for the late response. For the `-n` flag, you should pass the filename without extension as the value - in your case, only `dns_cf`.
