### ISSUE TITLE
Web UI crashing when script runs

### ISSUE THREAD

**Issue by sjdvda** [hungnguyenm/edgemax-acme#6]
Hi,

I'm getting a "503 Service Unavailable" error when I try to access the Web UI after the script runs.

The issue disappears when I change `kill_and_wait $(pidof lighttpd)` (line 71 in renew.acme.sh) to `kill $(pidof lighttpd)`. 

On my system (EdgeRouter-X v2.0.8), running `kill_and_wait $(pidof lighttpd)` gives the following error:
> vbash: kill_and_wait: command not found

Not sure if I did something wrong with the setup or there is an issue with the script.

**Comment by hungnguyenm** [comment]
Yup, I got the same issue too so I changed the command to `killall` instead.

`kill_and_wait` was a function in the script so it's not available in your shell.
