### ISSUE TITLE
renew.acme.sh does not kill lighttpd

### ISSUE THREAD

**Issue by rajiv** [hungnguyenm/edgemax-acme#7]
on ER-X running EdgeOS v1.10.11, when running as root:

```
root@edge:/config/scripts# /config/scripts/renew-edge.acme.sh
[Fri May 22 00:54:17 EDT 2020] Stopping gui service.
killall: Operation not supported
[Fri May 22 00:54:17 EDT 2020] Executing acme.sh.
...
```

and then of course later in the script:
```
...
[Fri May 22 00:55:10 EDT 2020] Reload success
[Fri May 22 00:55:10 EDT 2020] Starting gui service.
2020-05-22 00:55:10: (network.c.409) can't bind to port:  80 Address already in use 
```

is this related to #6?

**Comment by hungnguyenm** [comment]
Yeah, I don't have an ER-X running v1.x show I can't verify exactly but I guess the issue was due to the difference between v1.x and v2.x versions. I'll put of a fix real quick.

**Comment by hungnguyenm** [comment]
Please let me know if the fix works. Thank you!

**Comment by rajiv** [comment]
still an issue. cb010d7177636b55135c792d1c7ac3323e47fcd7 did not change or fix the issue. perhaps #9 will fix it?
